# fly.toml app configuration file generated for gorypto-news on 2024-02-02T17:17:16+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gorypto-news'
primary_region = 'sin'

[build]

[env]

[[services]]

[experimental]
entrypoint = ["/bin/server", "-limit=5"]
