# fly.toml app configuration file generated for gorypto-news on 2024-02-02T18:11:09+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gorypto-news'
primary_region = 'sin'

[experimental]
entrypoint = ['/bin/server', '-limit=3']

[build]

[[services]]
